## Group 5 Data Cleaning for Hennepin County Analysis

In [1]:
#Code Block 1
## import necessary libraries

import pandas as pd
import geopandas as gpd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

plt.style.use("seaborn-v0_8")
sns.set_style("whitegrid")

%matplotlib inline

In [2]:
#Code Block 2
## load in the data

data_pull = pd.read_csv('../../Data/Hennepin/mortgage_covenant_data-new.csv')
data_given = pd.read_csv('../../Data/mortgage_covenant_data.csv')

display(data_pull.info())
data_given.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100973 entries, 0 to 100972
Data columns (total 13 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   activity_year                      100973 non-null  int64
 1   census_tract                       99959 non-null   float64
 2   derived_race                       100973 non-null  object
 3   action_taken                       100973 non-null  int64
 4   loan_amount                        100973 non-null  float64
 5   property_value                     88614 non-null   object
 6   income                             88231 non-null   float64
 7   interest_rate                      83252 non-null   object
 8   tract_minority_population_percent  100973 non-null  float64
 9   tract_to_msa_income_percentage     100973 non-null  float64
 10  denial_reason-1                    100973 non-null  int64
 11  covenant_count                     100973 non-null  float64
 12  was_approved                       100973 non-null  bool
dtypes: bool(1), float64(6), int64(3), object(3)
memory usage: 9.3+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100931 entries, 0 to 100930
Data columns (total 14 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   activity_year                      100931 non-null  int64
 1   census_tract                       99915 non-null   float64
 2   derived_race                       100931 non-null  object
 3   action_taken                       100931 non-null  int64
 4   loan_amount                        100931 non-null  float64
 5   property_value                     83491 non-null   float64
 6   income                             88200 non-null   float64
 7   interest_rate                      78125 non-null   float64
 8   tract_minority_population_percent  100931 non-null  float64
 9   tract_to_msa_income_percentage     100931 non-null  float64
 10  denial_reason-1                    100931 non-null  int64
 11  covenant_count                     100931 non-null  float64
 12  was_approved                       100931 non-null  bool
 13  covenant_density                   11169 non-null   object
dtypes: bool(1), float64(8), int64(3), object(2)
memory usage: 10.1+ MB

In [3]:
#Code Block 3
## view the head of the data
display(data_pull.head())
data_given.head()

,activity_year,census_tract,derived_race,action_taken,loan_amount,property_value,income,interest_rate,tract_minority_population_percent,tract_to_msa_income_percentage,denial_reason-1,covenant_count,was_approved
0,2023,2.705302e+10,Race Not Available,1,305000.0,325000,65.0,6.500,38.48,83.64,10,13.0,True
1,2023,2.700305e+10,White,1,285000.0,295000,72.0,6.450,21.74,86.21,10,0.0,True
2,2023,2.703706e+10,White,1,365000.0,505000,175.0,7.490,18.62,130.45,10,0.0,True
3,2023,2.700305e+10,Asian,1,315000.0,335000,108.0,7.000,22.37,97.44,10,0.0,True
4,2023,2.700305e+10,White,1,255000.0,315000,304.0,7.500,31.70,61.47,10,0.0,True

,activity_year,census_tract,derived_race,action_taken,loan_amount,property_value,income,interest_rate,tract_minority_population_percent,tract_to_msa_income_percentage,denial_reason-1,covenant_count,was_approved,covenant_density
0,2023,2.703706e+10,Race Not Available,6,185000.0,195000.0,NaN,6.125,40.37,73.48,10,0.0,False,NaN
1,2023,2.714103e+10,Race Not Available,6,375000.0,385000.0,NaN,6.625,10.64,121.26,10,0.0,False,NaN
2,2023,2.702395e+10,Race Not Available,6,105000.0,105000.0,NaN,6.125,8.92,90.13,10,0.0,False,NaN
3,2023,2.717110e+10,Race Not Available,6,285000.0,285000.0,NaN,6.750,13.27,104.37,10,0.0,False,NaN
4,2023,2.715948e+10,Race Not Available,6,175000.0,175000.0,NaN,6.875,5.87,82.22,10,0.0,False,NaN

In [4]:
#Code Block 4
## view the missing values

print("Pulled Data Missing Values:")
display(data_pull.isnull().sum())

print("Given Data Missing Values:")
data_given.isnull().sum()

Pulled Data Missing Values:

activity_year                            0
census_tract                          1014
derived_race                             0
action_taken                             0
loan_amount                              0
property_value                       12359
income                               12742
interest_rate                        17721
tract_minority_population_percent        0
tract_to_msa_income_percentage           0
denial_reason-1                          0
covenant_count                           0
was_approved                             0
dtype: int64

Given Data Missing Values:

activity_year                            0
census_tract                          1016
derived_race                             0
action_taken                             0
loan_amount                              0
property_value                       17440
income                               12731
interest_rate                        22806
tract_minority_population_percent        0
tract_to_msa_income_percentage           0
denial_reason-1                          0
covenant_count                           0
was_approved                             0
covenant_density                     89762
dtype: int64

In [5]:
#Code Block 5
## fix data types

data_pull['property_value'] = pd.to_numeric(data_pull['property_value'], errors='coerce')
data_pull['interest_rate'] = pd.to_numeric(data_pull['interest_rate'], errors='coerce')

display(data_pull.info(), data_given.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100973 entries, 0 to 100972
Data columns (total 13 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   activity_year                      100973 non-null  int64
 1   census_tract                       99959 non-null   float64
 2   derived_race                       100973 non-null  object
 3   action_taken                       100973 non-null  int64
 4   loan_amount                        100973 non-null  float64
 5   property_value                     83503 non-null   float64
 6   income                             88231 non-null   float64
 7   interest_rate                      78140 non-null   float64
 8   tract_minority_population_percent  100973 non-null  float64
 9   tract_to_msa_income_percentage     100973 non-null  float64
 10  denial_reason-1                    100973 non-null  int64
 11  covenant_count                     100973 non-null  float64
 12  was_approved                       100973 non-null  bool
dtypes: bool(1), float64(8), int64(3), object(1)
memory usage: 9.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100931 entries, 0 to 100930
Data columns (total 14 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   activity_year                      100931 non-null  int64
 1   census_tract                       99915 non-null   float64
 2   derived_race                       100931 non-null  object
 3   action_taken                       100931 non-null  int64
 4   loan_amount                        100931 non-null  float64
 5   property_value                     83491 non-null   float64
 6   income                             88200 non-null   float64
 7   interest_rate                      78125 non-null   float64
 8   tract_minority_population_percent  100931 non-null  float64
 9   tract_to_msa_income_percentage     100931 non-null  float64
 10  denial_reason-1                    100931 non-null  int64
 11  covenant_count                     100931 non-null  float64
 12  was_approved                       100931 non-null  bool
 13  covenant_density                   11169 non-null   object
dtypes: bool(1), float64(8), int64(3), object(2)
memory usage: 10.1+ MB

None

None

In [6]:
#Code Block 6
## census tract formatting
print(type(data_pull['census_tract'][0]))

### convert to string to merge tract area for covenant density
data_pull['census_tract'].head()

<class 'numpy.float64'>

0    2.705302e+10
1    2.700305e+10
2    2.703706e+10
3    2.700305e+10
4    2.700305e+10
Name: census_tract, dtype: float64

In [7]:
#Code Block 7
## handle missing values
### drop rows with missing census data
data_pull = data_pull.dropna(subset=['census_tract'])

### fill nulls for property value and income
data_pull['property_value'] = data_pull['property_value'].fillna(data_pull['property_value'].median())
data_pull['income'] = data_pull['income'].fillna(data_pull['income'].median())

display(data_pull.info())
data_pull.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 99959 entries, 0 to 100972
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   activity_year                      99959 non-null  int64
 1   census_tract                       99959 non-null  float64
 2   derived_race                       99959 non-null  object
 3   action_taken                       99959 non-null  int64
 4   loan_amount                        99959 non-null  float64
 5   property_value                     99959 non-null  float64
 6   income                             99959 non-null  float64
 7   interest_rate                      77877 non-null  float64
 8   tract_minority_population_percent  99959 non-null  float64
 9   tract_to_msa_income_percentage     99959 non-null  float64
 10  denial_reason-1                    99959 non-null  int64
 11  covenant_count                     99959 non-null  float64
 12  was_approved                       99959 non-null  bool
dtypes: bool(1), float64(8), int64(3), object(1)
memory usage: 10.0+ MB

None

activity_year                            0
census_tract                             0
derived_race                             0
action_taken                             0
loan_amount                              0
property_value                           0
income                                   0
interest_rate                        22082
tract_minority_population_percent        0
tract_to_msa_income_percentage           0
denial_reason-1                          0
covenant_count                           0
was_approved                             0
dtype: int64

In [9]:
#Code Block 8 
## recreate covenant density feature
display(data_given['covenant_density'].value_counts())

## recreate covenant density feature for pulled data based on covenant count
bins = [0, 50, 100, 200, float('inf')]
labels = ['Low (1-50)', 'Medium (51-100)', 'High (101-200)', 'Very High (>200)']
data_pull['covenant_density'] = pd.cut(data_pull['covenant_count'], bins=bins, labels=labels, right=True)

# Verify the value counts for the new covenant_density column
display(data_pull['covenant_density'].value_counts())

### diagnostics
display(data_pull.info())
data_pull.isnull().sum()

covenant_density
Low (1-50)          4537
Very High (>200)    3140
Medium (51-100)     1772
High (101-200)      1720
Name: count, dtype: int64

covenant_density
Low (1-50)          4539
Very High (>200)    3140
Medium (51-100)     1772
High (101-200)      1720
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
Index: 99959 entries, 0 to 100972
Data columns (total 14 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   activity_year                      99959 non-null  int64
 1   census_tract                       99959 non-null  float64
 2   derived_race                       99959 non-null  object
 3   action_taken                       99959 non-null  int64
 4   loan_amount                        99959 non-null  float64
 5   property_value                     99959 non-null  float64
 6   income                             99959 non-null  float64
 7   interest_rate                      77877 non-null  float64
 8   tract_minority_population_percent  99959 non-null  float64
 9   tract_to_msa_income_percentage     99959 non-null  float64
 10  denial_reason-1                    99959 non-null  int64
 11  covenant_count                     99959 non-null  float64
 12  was_approved                       99959 non-null  bool
 13  covenant_density                   11171 non-null  category
dtypes: bool(1), category(1), float64(8), int64(3), object(1)
memory usage: 10.1+ MB

None

activity_year                            0
census_tract                             0
derived_race                             0
action_taken                             0
loan_amount                              0
property_value                           0
income                                   0
interest_rate                        22082
tract_minority_population_percent        0
tract_to_msa_income_percentage           0
denial_reason-1                          0
covenant_count                           0
was_approved                             0
covenant_density                     88788
dtype: int64

In [13]:
#Code Block 9
## fill the missing values for covenant density with 0 (tracts with no covenants)

## Add 0 as a category to the covenant_density column
data_pull['covenant_density'] = data_pull['covenant_density'].cat.add_categories([0])

## Fill the missing values for covenant density with 0 (tracts with no covenants)
data_pull['covenant_density'] = data_pull['covenant_density'].fillna(0)

## Check for remaining missing values
data_pull.isnull().sum()

activity_year                            0
census_tract                             0
derived_race                             0
action_taken                             0
loan_amount                              0
property_value                           0
income                                   0
interest_rate                        22082
tract_minority_population_percent        0
tract_to_msa_income_percentage           0
denial_reason-1                          0
covenant_count                           0
was_approved                             0
covenant_density                         0
dtype: int64

In [14]:
#Code Block 10
## do the same for the given data

display(data_given.info())
data_pull.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100931 entries, 0 to 100930
Data columns (total 14 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   activity_year                      100931 non-null  int64
 1   census_tract                       99915 non-null   float64
 2   derived_race                       100931 non-null  object
 3   action_taken                       100931 non-null  int64
 4   loan_amount                        100931 non-null  float64
 5   property_value                     83491 non-null   float64
 6   income                             88200 non-null   float64
 7   interest_rate                      78125 non-null   float64
 8   tract_minority_population_percent  100931 non-null  float64
 9   tract_to_msa_income_percentage     100931 non-null  float64
 10  denial_reason-1                    100931 non-null  int64
 11  covenant_count                     100931 non-null  float64
 12  was_approved                       100931 non-null  bool
 13  covenant_density                   11169 non-null   object
dtypes: bool(1), float64(8), int64(3), object(2)
memory usage: 10.1+ MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 99959 entries, 0 to 100972
Data columns (total 14 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   activity_year                      99959 non-null  int64
 1   census_tract                       99959 non-null  float64
 2   derived_race                       99959 non-null  object
 3   action_taken                       99959 non-null  int64
 4   loan_amount                        99959 non-null  float64
 5   property_value                     99959 non-null  float64
 6   income                             99959 non-null  float64
 7   interest_rate                      77877 non-null  float64
 8   tract_minority_population_percent  99959 non-null  float64
 9   tract_to_msa_income_percentage     99959 non-null  float64
 10  denial_reason-1                    99959 non-null  int64
 11  covenant_count                     99959 non-null  float64
 12  was_approved                       99959 non-null  bool
 13  covenant_density                   99959 non-null  category
dtypes: bool(1), category(1), float64(8), int64(3), object(1)
memory usage: 10.1+ MB

In [15]:
#Code Block 11
## fixing the given data

### convert and reformat census tract string
data_given['census_tract'] = (
    data_given['census_tract']
    .round()
    .astype('Int64')
    .astype(str)
    .str.zfill(11)
)

### drop rows with missing census data
data_given = data_given.dropna(subset=['census_tract'])

### fill nulls for property value and income
data_given['property_value'] = data_given['property_value'].fillna(data_given['property_value'].median())
data_given['income'] = data_given['income'].fillna(data_given['income'].median())

### fill nulls for covenant density with 0
data_given['covenant_density'] = data_given['covenant_density'].fillna(0)

display(data_given.info())
data_given.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100931 entries, 0 to 100930
Data columns (total 14 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   activity_year                      100931 non-null  int64
 1   census_tract                       100931 non-null  object
 2   derived_race                       100931 non-null  object
 3   action_taken                       100931 non-null  int64
 4   loan_amount                        100931 non-null  float64
 5   property_value                     100931 non-null  float64
 6   income                             100931 non-null  float64
 7   interest_rate                      78125 non-null   float64
 8   tract_minority_population_percent  100931 non-null  float64
 9   tract_to_msa_income_percentage     100931 non-null  float64
 10  denial_reason-1                    100931 non-null  int64
 11  covenant_count                     100931 non-null  float64
 12  was_approved                       100931 non-null  bool
 13  covenant_density                   100931 non-null  object
dtypes: bool(1), float64(7), int64(3), object(3)
memory usage: 10.1+ MB

None

activity_year                            0
census_tract                             0
derived_race                             0
action_taken                             0
loan_amount                              0
property_value                           0
income                                   0
interest_rate                        22806
tract_minority_population_percent        0
tract_to_msa_income_percentage           0
denial_reason-1                          0
covenant_count                           0
was_approved                             0
covenant_density                         0
dtype: int64

In [16]:
#Code Block 12
## save the cleaned datasets
if not os.path.exists('../../Data/Hennepin/cleaned'):
    os.makedirs('../../Data/Hennepin/cleaned')

data_pull.to_csv('../../Data/Hennepin/cleaned/cleaned_mortgage_covenant_data_pull.csv', index = False)
data_given.to_csv('../../Data/Hennepin/cleaned/cleaned_mortgage_covenant_data.csv', index = False)